[build-system]
    requires = ["setuptools", "wheel"]
    build-backend = "setuptools.build_meta"

[project]
    name = "bottau"
    version = "0.0.1"
    description = "A quant trading bot."

[tool.setuptools.packages.find]
    where = ["src"]
